<?php

namespace TaskPlannerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    
    public function displayLogedUsersCategories($userId) {
        
        $category = $this->getEntityManager()->createQuery(
        'SELECT c FROM TaskPlannerBundle:Category c WHERE c.user = :userId'
        )->setParameter('userId', $userId)
        ->getResult();
        
        return $category;
    }
}
